# Generated by Django 4.2.3 on 2023-07-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('key_context', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255, null=True)),
                ('org_id', models.CharField(max_length=255, null=True)),
                ('course_id', models.CharField(max_length=255, null=True)),
                ('agent', models.CharField(max_length=255, null=True)),
                ('referer', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('key_event', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('event_source', models.CharField(max_length=255)),
                ('page', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('key_context', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datosUCH.context')),
            ],
        ),
        migrations.AddField(
            model_name='context',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datosUCH.user'),
        ),
    ]
