# Generated by Django 4.2.3 on 2023-07-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosUCH', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='event',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
